### ISSUE TITLE
Interface glitch in &music

### ISSUE THREAD

**Issue by rmasoni** [euphoria-io/heim#32]
For some reason the &music room is looking like this on Safari 8.0.8 (Yosemite):

![&music](https://cloud.githubusercontent.com/assets/62244/9361113/57c1aae4-4670-11e5-8056-f5363631ddaf.png)

See the sidebar with the YouTube player? It's really narrow.

I didn't have this problem yesterday on Safari 9 (El Capitan).

**Comment by rmasoni** [comment]
Now the player is taking up the whole screen:

![screen shot 2015-08-19 at 13 49 09](https://cloud.githubusercontent.com/assets/62244/9362831/38b476e6-4679-11e5-8475-583b2126afcb.png)

**Comment by rmasoni** [comment]
This seems to have been fixed on 017106253b204ad8d8b9318e11b618e55cf06cc6.

**Comment by chromakode** [comment]
Thanks for getting to the bottom of this @rmasoni!
