### ISSUE TITLE
Exempt ™ from emoji conversion

### ISSUE THREAD

**Issue by chromakode** [euphoria-io/heim#44]
The emojified "™" character is large and bold. It's not what most people intended to enter. We'll want to exempt this from the twemoji transformation somehow.

**Comment by Garmelon** [comment]
Or change the emoji itself to look more like the ™. I like to be able to type :tm: to use that emoji.

**Comment by chromakode** [comment]
Fixed by @CylonicRaider in https://github.com/euphoria-io/heim/pull/53
