### ISSUE TITLE
Autocomplete autocompletes name of disconnected clients

### ISSUE THREAD

**Issue by Garmelon** [euphoria-io/heim#63]
To reproduce:
Sit in a room and wait until anything vanishes from the nick list (bots or people work)
Try to autocomplete their name

**Comment by chromakode** [comment]
This is a new behavior that came as a side-effect of some user list changes. I don't view it as problematic, so I didn't attempt to fix it. Is this behavior causing problems for you?

**Comment by Garmelon** [comment]
It is annoying when using BotBot in &bots as it tends to autocomplete names of "dead" bots

**Comment by chromakode** [comment]
Ah I see, good point. I'll look into this further. Should be an easy change to make.

**Comment by CylonicRaider** [comment]
I thought it was intentional, for mentioning people who did leave not long ago.

**Comment by jedevc** [comment]
Maybe a delay of maybe quarter of an hour?

**Comment by Garmelon** [comment]
Maybe that still doesn't sound good - I usually don't wait for a quarter of an hour between mentioning bots in &bots.

**Comment by jedevc** [comment]
Yeah, good point, but sometimes it is useful to mention people after they leave.

**Comment by chromakode** [comment]
https://github.com/euphoria-io/heim/commit/5680054152486406cb83cb768a86ca2e044c00f2
