### ISSUE TITLE
who-reply not documented

### ISSUE THREAD

**Issue by CylonicRaider** [euphoria-io/heim#67]
[The documentation of the `who` command](https://github.com/euphoria-io/heim/blob/9408cdeeb9db6d157ca909d58d04e110b72eefc9/doc/api.md#who) claims incorrectly the `who-reply` packet "ha[d] no fields", while the back-end (as of 2016-01-07) returns a object with a single `listing` member (containing a list of `SessionView`s) instead.

**Comment by logan** [comment]
Fixed in d80033f.
