### ISSUE TITLE
Character Limit on Posts limits bots

### ISSUE THREAD

**Issue by Baconchicken42** [euphoria-io/heim#81]
as of March 22, 2016 I was working on a new addition to @EmoBot. If you're ever in &xkcd you'll probably know what it is. Anyways, the code for it is super long. So the character limit blocks out most of it, even though the code is still there and @BotBot can still read it and create the bot. However, today I found that one of the new things I added wasn't working. I added a !test command at the end of the code, and that didn't work either. Is there another character limit that stops the post entirely, is this a botbot issue, or something else entirely? Any help would be appreciated.

**Comment by CylonicRaider** [comment]
Messages are truncated to 4096 characters except when submitting one or using the `get-message` command; those are limited to 1MiB of UTF-8. @BotBot was specifically patched to support long messages (https://github.com/ArkaneMoose/BotBot/pull/27)... but all that was way after this issue, so it is probably obsolete.

**Comment by Baconchicken42** [comment]
Why am I getting this email now, and not at any of the myriad other times i
put in botbot code that got truncated?

**Comment by CylonicRaider** [comment]
To quote myself,
[Xyzzy] /me is meanwhile going through the Euphoria issues and commenting on them

**Comment by Baconchicken42** [comment]
Ok then

**Comment by ArkaneMoose** [comment]
To my knowledge, any code shorter than one 1 MiB should be accepted by BotBot because BotBot uses Euphoria's `get-message` API to retrieve the non-truncated version of the message. (This has been implemented since ArkaneMoose/BotBot@7d1ec15.) However, the code may still appear to be truncated in the Euphoria interface. (I tested this in &bots just now, and it appears to be working; code that was truncated was correctly handled.)

**Comment by CylonicRaider** [comment]
> To my knowledge, any code shorter than one 1 MiB should be accepted by BotBot because BotBot uses Euphoria's get-message API to retrieve the non-truncated version of the message. (This has been implemented since ArkaneMoose/BotBot@7d1ec15.)

...Just as I pointed out above. :smile:

> @BotBot was specifically patched to support long messages (ArkaneMoose/BotBot#27)...

Aside from all that, I vote to close this issue.

**Comment by ArkaneMoose** [comment]
Yep, sorry. I also vote to close.

**Comment by kaliumxyz** [comment]
Xyzzers pl0x close.

**Comment by CylonicRaider** [comment]
...I fear that is beyond my power... @logan pl0x?

**Comment by Baconchicken42** [comment]
while i'm in this email thread, I vote to close as well, I guess?

**Comment by CylonicRaider** [comment]
Actually, *you* might be able to close it as well, @Baconchicken42.

**Comment by Baconchicken42** [comment]
What do you mean?

**Comment by totallyhuman** [comment]
Hot? Hot? I want to be here!

**Comment by kaliumxyz** [comment]
You can close your own issues.

**Comment by totallyhuman** [comment]
You gotta get to the website though. You can't do it via email.

**Comment by kaliumxyz** [comment]
unlike in real life.

**Comment by CylonicRaider** [comment]
@Baconchicken42, if you care to log in to GitHub, you should be able to close the issue from the button in the comment box.

**Comment by Baconchicken42** [comment]
You know, I forgot entirely that I even opened this. Funnily enough the problem was that I forgot a parenthese and I fixed it a while ago.

**Comment by totallyhuman** [comment]
We did it, internet!

**Comment by CylonicRaider** [comment]
Quick poll, should Euphoria have embedded emoji replies? :laughing:

**Comment by PouncySilverkitten** [comment]
Yay us!

**Comment by Baconchicken42** [comment]
Yay!

**Comment by CylonicRaider** [comment]
> Quick poll, should Euphoria have embedded emoji replies? :laughing:

In addition, should those accumulate into “karma” points displayed on a user's profile?

**Comment by totallyhuman** [comment]
You'd have to implement profile pages as well, though.

**Comment by CylonicRaider** [comment]
> You'd have to implement profile pages as well, though.

Killjoy! :-1:

**Comment by totallyhuman** [comment]
😛

**Comment by kaliumxyz** [comment]
Just give everyone a score, I encourage said score to be based on.... some post count and emoji usage metric.

**Comment by totallyhuman** [comment]
Or slang usage.

**Comment by CylonicRaider** [comment]
This thread keeps giving and giving. :laughing:

**Comment by totallyhuman** [comment]
Wait a minute... can you call this a thread?

**Comment by CylonicRaider** [comment]
Yes, this is an oldschool forum thread.

**Comment by totallyhuman** [comment]
In which case, threading was boring.
